version: 0.0
resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: github-lambda-demo2
        Handler: lambda_function.hello
        Role: arn:aws:iam::274518127443:role/service-role/your-lambda-role
        CodeUri: s3://github-to-lambda-bucket/deployment_package.zip
        Runtime: python3.11
        Timeout: 10
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 60
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
