version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
post_build:
  commands:
    - echo "Copying deployment package to S3..."
    - aws s3 cp deployment_package.zip s3://github-to-lambda-bucket/
artifacts:
  files:
    - appspec.yml
    - deployment_package.zip

